### ISSUE TITLE
Module webkit not found?

### ISSUE THREAD

**Issue by markknochen1** [andresriancho/w3af#14190]
When i start w3af_gui i get this error:

`Python[68588:5560522] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/Users/markknochen/Downloads/w3af-master/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/Users/markknochen/Downloads/w3af-master/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit`

I can't found this module named "webkit" ...

is there a solution for this problem?

thx

Mark

**Comment by treyduffy** [comment]
Same issue.

Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/Users/trey/Downloads/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/Users/trey/Downloads/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit


On OSX 10.10.1

gtksourceview and gtk2 are installed and linked properly

w3af_console works

**Comment by mastermindg** [comment]
On Ubuntu had the same issue when installing w3af for the first time today. Got past it with:

```sudo apt-get install python-webkit python-webkit-dev```

**Comment by crystalstorm** [comment]
I had the same problem on OS X, fixed it with macports:
`sudo port install py27-webkitgtk`

**Comment by excalibur44** [comment]
I had the same problem on Kali Linux, but `python-webkit python-webkit-dev` is not in Kali repository. So I install it manually:

```
wget http://ftp.cn.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb
dpkg -i python-support_1.0.15_all.deb

wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit_1.1.8-3_amd64.deb
dpkg -i python-webkit_1.1.8-3_amd64.deb

apt install python-gtk2-dev
wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit-dev_1.1.8-3_all.deb
dpkg -i python-webkit-dev_1.1.8-3_all.deb
```

Sorry for my bad english.

**Comment by Chiel92** [comment]
Wasn't enough for me. I had to use the following commands to get the GUI started.

```bash
git clone --depth 1 https://github.com/andresriancho/w3af.git
cd w3af/
apt install graphviz
pip install pybloomfiltermmap==0.3.14
apt install libssl-dev
apt install libxml2 libxslt
apt install libxml2-dev libxslt
apt install libxml2-dev libxslt-dev
pip install pyopenssl
apt install zlib1g-dev
./w3af_console 
bash /tmp/w3af_dependency_install.sh

echo
echo "Console version seems to be working now."
echo "Installing dependencies for GUI."
echo

wget http://ftp.cn.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb
dpkg -i python-support_1.0.15_all.deb

wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit_1.1.8-3_amd64.deb
dpkg -i python-webkit_1.1.8-3_amd64.deb

apt install python-gtk2-dev
wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit-dev_1.1.8-3_all.deb
dpkg -i python-webkit-dev_1.1.8-3_all.deb

apt --fix-broken install
apt install python-gtksourceview2

./w3af_gui
bash /tmp/w3af_dependency_install.sh
```

**Comment by 1522402210** [comment]
@crystalstorm 
sudo port install py27-webkitgtk       
--->  Computing dependencies for py27-webkitgtk
The following dependencies will be installed: 
 ImageMagick
 Xft2
 at-spi2-atk
 at-spi2-core
 autoconf
 autoconf-archive
 automake
 bison
 bison-runtime
 boost
 cctools
 ctags
 curl
 cython_select
 dblatex
 dbus
 dejavu-fonts
 djvulibre
 docbook-xml
 docbook-xml-4.1.2
 docbook-xml-4.2
 docbook-xml-4.3
 docbook-xml-4.4
 docbook-xml-4.5
 docbook-xml-5.0
 docbook-xsl
 enchant
 fftw-3
 flex
 gawk
 gd2
 gdk-pixbuf2
 geoclue2
 ghostscript
 giflib
 glib-networking
 gnome-common
 graphite2
 graphviz
 gsettings-desktop-schemas
 gstreamer1
 gstreamer1-gst-plugins-base
 gtk-doc
 gtk2
 gtk3
 gts
 harfbuzz
 harfbuzz-icu
 hicolor-icon-theme
 icu
 ilmbase
 intltool
 isl
 itstool
 jbig2dec
 json-glib
 kerberos5
 ld64
 ld64-latest
 libLASi
 libcomerr
 libcxx
 libepoxy
 libgcc
 libgcrypt
 libglade2
 libgpg-error
 libidn2
 libmpc
 libnetpbm
 libpaper
 libproxy
 libpsl
 libraw
 libsecret
 libsoup
 libunistring
 libzzip
 llvm-5.0
 llvm_select
 m4
 mesa
 mpfr
 nosetests_select
 openexr
 p5.26-encode-locale
 p5.26-file-listing
 p5.26-getopt-long
 p5.26-html-form
 p5.26-html-parser
 p5.26-html-tagset
 p5.26-http-cookies
 p5.26-http-daemon
 p5.26-http-date
 p5.26-http-message
 p5.26-http-negotiate
 p5.26-io-html
 p5.26-io-socket-ssl
 p5.26-libwww-perl
 p5.26-lwp-mediatypes
 p5.26-lwp-protocol-https
 p5.26-mozilla-ca
 p5.26-net-http
 p5.26-net-libidn
 p5.26-net-ssleay
 p5.26-pathtools
 p5.26-scalar-list-utils
 p5.26-sub-name
 p5.26-sub-uplevel
 p5.26-test-exception
 p5.26-test-nowarnings
 p5.26-test-warn
 p5.26-try-tiny
 p5.26-uri
 p5.26-www-robotrules
 p5.26-xml-parser
 pango
 perl5
 perl5.26
 pgf
 poppler
 poppler-data
 potrace
 py27-cairo
 py27-cython
 py27-gobject
 py27-libxml2
 py27-nose
 py27-numpy
 py27-pygtk
 py36-anytree
 py36-lxml
 py36-pygments
 py36-setuptools
 py36-six
 pygments_select
 python36
 python3_select
 readline
 source-highlight
 texlive-basic
 texlive-bin
 texlive-common
 texlive-fonts-recommended
 texlive-latex
 texlive-latex-extra
 texlive-latex-recommended
 texlive-math-science
 texlive-pictures
 urw-fonts
 vala
 webkit-gtk
 webp
 xar
 xmlcatmgr
 xorg-compositeproto
 xorg-damageproto
 xorg-dri2proto
 xorg-glproto
 xorg-libXaw
 xorg-libXcomposite
 xorg-libXdamage
 xorg-libXmu
 xorg-libXp
 xorg-libXt
 xorg-libXtst
 xorg-libXxf86vm
 xorg-libice
 xorg-libsm
 xorg-printproto
 xorg-recordproto
 xorg-xf86vidmodeproto
 xpm
Continue? [Y/n]: Y
--->  Fetching archive for gdk-pixbuf2
--->  Attempting to fetch gdk-pixbuf2-2.36.11_0+x11.darwin_16.x86_64.tbz2 from http://kmq.jp.packages.macports.org/gdk-pixbuf2
--->  Attempting to fetch gdk-pixbuf2-2.36.11_0+x11.darwin_16.x86_64.tbz2.rmd160 from http://kmq.jp.packages.macports.org/gdk-pixbuf2
--->  Installing gdk-pixbuf2 @2.36.11_0+x11
--->  Activating gdk-pixbuf2 @2.36.11_0+x11
Error: Failed to activate gdk-pixbuf2: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_gdk-pixbuf2/gdk-pixbuf2/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port py27-webkitgtk failed

**Comment by n1rv4n4** [comment]
`sudo apt install python-webkit`

Solves the problem.

**Comment by ROHAN-TANDEL** [comment]
thanks @excalibur44  , It helped me to fix my problem,
after that I did,
sudo apt install python-webkit
sudo apt --fix-broken install
and
sudo apt-get install python-gtksourceview2

**Comment by ROHAN-TANDEL** [comment]
I am sure the issue is fixed for op. please close this issue.

**Comment by edermi** [comment]
Same issue on Kali, manually installing the Debian packages does not solve the issue for me.

**Comment by sivaarja** [comment]
> Wasn't enough for me. I had to use the following commands to get the GUI started.
> 
> ```shell
> git clone --depth 1 https://github.com/andresriancho/w3af.git
> cd w3af/
> apt install graphviz
> pip install pybloomfiltermmap==0.3.14
> apt install libssl-dev
> apt install libxml2 libxslt
> apt install libxml2-dev libxslt
> apt install libxml2-dev libxslt-dev
> pip install pyopenssl
> apt install zlib1g-dev
> ./w3af_console 
> bash /tmp/w3af_dependency_install.sh
> 
> echo
> echo "Console version seems to be working now."
> echo "Installing dependencies for GUI."
> echo
> 
> wget http://ftp.cn.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb
> dpkg -i python-support_1.0.15_all.deb
> 
> wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit_1.1.8-3_amd64.deb
> dpkg -i python-webkit_1.1.8-3_amd64.deb
> 
> apt install python-gtk2-dev
> wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit-dev_1.1.8-3_all.deb
> dpkg -i python-webkit-dev_1.1.8-3_all.deb
> 
> apt --fix-broken install
> apt install python-gtksourceview2
> 
> ./w3af_gui
> bash /tmp/w3af_dependency_install.sh
> ```

"Thanks a lot, @Chiel92 . it worked for me, I am using Parrot Security."
uname -a : "Linux parrot 5.1.0-parrot1-3t-amd64 #1 SMP Parrot 5.1.3-1parrot1.3t (2019-05-20) x86_64 GNU/Linux"

**Comment by changtraisitinh** [comment]
> > Wasn't enough for me. I had to use the following commands to get the GUI started.
> > ```shell
> > git clone --depth 1 https://github.com/andresriancho/w3af.git
> > cd w3af/
> > apt install graphviz
> > pip install pybloomfiltermmap==0.3.14
> > apt install libssl-dev
> > apt install libxml2 libxslt
> > apt install libxml2-dev libxslt
> > apt install libxml2-dev libxslt-dev
> > pip install pyopenssl
> > apt install zlib1g-dev
> > ./w3af_console 
> > bash /tmp/w3af_dependency_install.sh
> > 
> > echo
> > echo "Console version seems to be working now."
> > echo "Installing dependencies for GUI."
> > echo
> > 
> > wget http://ftp.cn.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb
> > dpkg -i python-support_1.0.15_all.deb
> > 
> > wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit_1.1.8-3_amd64.deb
> > dpkg -i python-webkit_1.1.8-3_amd64.deb
> > 
> > apt install python-gtk2-dev
> > wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit-dev_1.1.8-3_all.deb
> > dpkg -i python-webkit-dev_1.1.8-3_all.deb
> > 
> > apt --fix-broken install
> > apt install python-gtksourceview2
> > 
> > ./w3af_gui
> > bash /tmp/w3af_dependency_install.sh
> > ```
> 
> "Thanks a lot, @Chiel92 . it worked for me, I am using Parrot Security."
> uname -a : "Linux parrot 5.1.0-parrot1-3t-amd64 #1 SMP Parrot 5.1.3-1parrot1.3t (2019-05-20) x86_64 GNU/Linux"

i tried on Kali, but it not working for me :(

**Comment by wan721** [comment]
> Wasn't enough for me. I had to use the following commands to get the GUI started.
> 
> ```shell
> git clone --depth 1 https://github.com/andresriancho/w3af.git
> cd w3af/
> apt install graphviz
> pip install pybloomfiltermmap==0.3.14
> apt install libssl-dev
> apt install libxml2 libxslt
> apt install libxml2-dev libxslt
> apt install libxml2-dev libxslt-dev
> pip install pyopenssl
> apt install zlib1g-dev
> ./w3af_console 
> bash /tmp/w3af_dependency_install.sh
> 
> echo
> echo "Console version seems to be working now."
> echo "Installing dependencies for GUI."
> echo
> 
> wget http://ftp.cn.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb
> dpkg -i python-support_1.0.15_all.deb
> 
> wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit_1.1.8-3_amd64.deb
> dpkg -i python-webkit_1.1.8-3_amd64.deb
> 
> apt install python-gtk2-dev
> wget http://ftp.cn.debian.org/debian/pool/main/p/pywebkitgtk/python-webkit-dev_1.1.8-3_all.deb
> dpkg -i python-webkit-dev_1.1.8-3_all.deb
> 
> apt --fix-broken install
> apt install python-gtksourceview2
> 
> ./w3af_gui
> bash /tmp/w3af_dependency_install.sh
> ```

This works for me on Debian 9.7 (Stretch)

**Comment by six2dez** [comment]
Finally! This is my entire process to install and run w3af_gui for **Kali 2019.3** which I think is the common issue:

```bash
git clone --depth 1 https://github.com/andresriancho/w3af.git
cd w3af/
apt install graphviz libssl-dev libxml2 libxslt1.1 libxml2-dev libxslt-dev zlib1g-dev
pip install pybloomfiltermmap==0.3.14
pip install pyopenssl
./w3af_console

apt install libicu57 libpango1.0 libegl1-mesa
wget http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-1.0-0_2.4.11-3_amd64.deb 
dpkg -i libjavascriptcoregtk-1.0-0_2.4.11-3_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/libwebkitgtk-1.0-0_2.4.11-3_amd64.deb
dpkg -i libwebkitgtk-1.0-0_2.4.11-3_amd64.deb
dpkg -i python-webkit_1.1.8-3_amd64.deb
bash /tmp/w3af_dependency_install.sh
./w3af_gui
```
Thanks to @Chiel92 for the initial foothold.
I hope this will help you :)
